In [21]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, minmax_scale, maxabs_scale, robust_scale
from sklearn.metrics import roc_auc_score,recall_score, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [26]:
x_test.head()

총구매액     최대구매액       환불금액 주구매상품 주구매지점  내점일수    내점당구매건수    주말방문비율  구매주기
0   70900400  22000000   70900400    골프  부산본점    13   1.461538  0.789474    26
1  310533100  38558000  310533100   농산물   잠실점    90   2.433333  0.369863     3
2  305264140  14825000  305264140  가공식품  본  점   101  14.623762  0.083277     3
3    7594080   5225000    7594080  주방용품  부산본점     5   2.000000  0.000000    47
4    1795790   1411200    1795790   수산품  청량리점     3   2.666667  0.125000     8

In [27]:
# 스케일링
x_train['주구매상품'].head()
x_train[['주구매상품','주구매지점']]= x_train.loc[:,['주구매상품','주구매지점']].apply(LabelEncoder().fit_transform)
x_test[['주구매상품','주구매지점']]= x_test.loc[:,['주구매상품','주구매지점']].apply(LabelEncoder().fit_transform)

In [28]:
x_train.head()

총구매액     최대구매액      환불금액  주구매상품  주구매지점  내점일수   내점당구매건수    주말방문비율  구매주기
0  68282840  11264000  68282840      5      0    19  3.894737  0.527027    17
1   2136000   2136000   2136000     21     19     2  1.500000  0.000000     1
2   3197000   1639000   3197000      6      1     2  2.000000  0.000000     1
3  16077620   4935000  16077620      5      2    18  2.444444  0.318182    16
4  29050000  24000000  29050000     15      8     2  1.500000  0.000000    85

In [36]:
# 로지스틱
model = LogisticRegression().fit(x_train,y_train)
model.score(x_train, y_train) # 0.623
pred = model.predict_proba(x_test)
pred


array([[0.58110572, 0.41889428],
       [0.75936401, 0.24063599],
       [0.73422022, 0.26577978],
       ...,
       [0.71708579, 0.28291421],
       [0.59003753, 0.40996247],
       [0.50073886, 0.49926114]])

In [35]:
# SVM
model_svm = SVC(C=10000, gamma=0.001, probability=True).fit(x_train, y_train)
model_svm.score(x_train,y_train)
model_svm.predict_proba(x_test)

array([[0.62275189, 0.37724811],
       [0.62275189, 0.37724811],
       [0.62275189, 0.37724811],
       ...,
       [0.62275189, 0.37724811],
       [0.62275189, 0.37724811],
       [0.62275189, 0.37724811]])

In [39]:
# Gradient Boost
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier().fit(x_train,y_train)
gbc.predict_proba(x_test)
gbc.score(x_train,y_train)

0.7085714285714285

In [42]:
# RandomForest
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier().fit(x_train,y_train)
rfc.predict_proba(x_test)
# rfc.score(x_train,y_train)
roc_auc_score()

array([[0.27, 0.73],
       [0.79, 0.21],
       [0.49, 0.51],
       ...,
       [0.56, 0.44],
       [0.57, 0.43],
       [0.33, 0.67]])

In [45]:
import seaborn as sns
sns.load_dataset('titanic')

ModuleNotFoundError: No module named 'seaborn'